### ISSUE TITLE
всем похуй всем похуй

### ISSUE THREAD

**Issue by CrystalCL** [EurekaEffect/zeon-crack#6]
всем же наверное похуй, что ньючанкс на режекте появился после слива артикхака, также всем похуй на то, что эта версия даже не выпускалась. А следовательно хули вы пиздите, если кроме меня ее никто не юзал. Следовательно еврека еблан и тот еще клоун

**Comment by EurekaEffect** [comment]
че ты выспал, даже если ньючанк в реджекте позже появились, в бличхаке
идентичные еще до артикхака были
плюс даже похуй на нч, остальное ты спиздил

вс, 2 янв. 2022 г., 12:06 CRystalCLient ***@***.***>:

**Comment by CrystalCL** [comment]
чел, высрал ты. Че ты пиздишь, если я эту версию даже не релизнул. Мб я ее только для себя делал? не? Или у тебя мозгов додуматься не хватило?

**Comment by EurekaEffect** [comment]
делал для себя, скинул для юзеров НЦ ДА ТИПА

вс, 2 янв. 2022 г., 13:18 CRystalCLient ***@***.***>:

**Comment by CrystalCL** [comment]
Где я скинул юзерам, брухич? Покажи блять! ГДЕ?
